printWidth: 79
useTabs: false
tabWidth: 2
semi: true
singleQuote: true
bracketSpacing: true
trailingComma: 'all'
arrowParens: 'avoid'
proseWrap: 'always'
overrides:
  - files:
      - '*.html'
    options:
      singleQuote: false
      printWidth: 100
